volans_dbt:
  target: prod
  outputs:
    prod:
      project: clinica-volans
      type: bigquery
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: us-east1
      method: oauth
      priority: interactive
      threads: 4
      schema: data